# DVC pipeline definition for Iikshana data pipeline (data at repo root data/)
# Run with: dvc repro (from data-pipeline/)
# Track data with: dvc add ../data/raw/RAVDESS ../data/processed/dev ../data/processed/test ../data/processed/holdout ../data/legal_glossary

stages:
  download:
    cmd: python -m scripts.download_datasets
    deps:
      - scripts/download_datasets.py
      - scripts/utils.py
      - config/datasets.yaml
    outs:
      - ../data/raw

  preprocess:
    cmd: python -m scripts.preprocess_audio && python -m scripts.stratified_split
    deps:
      - scripts/preprocess_audio.py
      - scripts/stratified_split.py
      - scripts/utils.py
      - config/datasets.yaml
      - ../data/raw
    outs:
      - ../data/processed/dev
      - ../data/processed/test
      - ../data/processed/holdout

  validate:
    cmd: python -m scripts.validate_schema
    deps:
      - scripts/validate_schema.py
      - ../data/processed/dev
      - ../data/processed/test
      - ../data/processed/holdout
    outs:
      - ../data/processed/audio_schema.json
      - ../data/processed/quality_report.json

  bias:
    cmd: python -m scripts.detect_bias
    deps:
      - scripts/detect_bias.py
      - ../data/processed/dev
      - ../data/processed/test
      - ../data/processed/holdout
    outs:
      - ../data/processed/bias_report.json

  evaluate:
    cmd: python -m scripts.evaluate_models
    deps:
      - scripts/evaluate_models.py
      - ../data/processed/dev
      - ../data/processed/test
      - ../data/processed/holdout
    outs:
      - ../data/processed/evaluation_metrics.json
